databases:
  - name: client-project-db
    engine: mongodb
    version: 6
    region: oregon
    plan: starter

services:
  - type: web
    name: client-project-backend
    env: node
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: "3000"
      - key: MONGODB_URI
        fromDatabase:
          name: client-project-db
    autoDeploy: true
